version: "3.8"
services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db
  backend:
    build: ./todo-backend
    ports:
      - "5000:5000"
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongodb
  frontend:
    build: ./todo-fronted
    ports:
      - "80:80"
    stdin_open: true
    tty: true
    depends_on:
      - backend
volumes:
  data:
  logs: